name: Guest Count Check

on:
  schedule:
    # Run every 15 minutes
    - cron: '*/15 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-guest-counts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Cache guest count data
      uses: actions/cache@v3
      with:
        path: |
          *.pkl
        key: guest-count-data-${{ runner.os }}-${{ github.run_number }}
        restore-keys: |
          guest-count-data-${{ runner.os }}-
    
    - name: Run guest count check
      env:
        SCRIPT_ENABLED: ${{ secrets.SCRIPT_ENABLED }}
        C7_APP_ID: ${{ secrets.C7_APP_ID }}
        C7_API_KEY: ${{ secrets.C7_API_KEY }}
        C7_TENANT_ID: ${{ secrets.C7_TENANT_ID }}
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
        Email_1: ${{ secrets.EMAIL_1 }}
        Phone_1: ${{ secrets.PHONE_1 }}
        SMTP_EMAIL: ${{ secrets.SMTP_EMAIL }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      run: |
        python guest-count-alert-script.py